### ISSUE TITLE
`cgi` module removed in Python 3.13

### ISSUE THREAD

**Issue by forrestfwilliams** [ASFHyP3/hyp3-lib#300]
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-3211

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

`fetch.py` uses the module `cgi`, which was depreciated in Python 3.11. The module won't be removed until Python 3.13 but we should update `fetch.py` to not use this module.

Alternatives are listed in [PEP 594](https://peps.python.org/pep-0594/#cgi).

**Comment by jtherrmann** [comment]
Fixed by https://github.com/ASFHyP3/hyp3-lib/pull/314
